"use client";
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import type {Session,User} from '@supabase/supabase-js';
import {createClient} from '@/lib/supabase/client';
import {getCurrentProfile} from '@/lib/repositories/profile';

type AuthContextValue={session:Session|null;user:User|null;profile:Record<string,unknown>|null;organization:Record<string,unknown>|null;role:string;loading:boolean;signOut:()=>Promise<void>};
const AuthContext=createContext<AuthContextValue>({session:null,user:null,profile:null,organization:null,role:'Viewer',loading:true,signOut:async()=>{}});
export function AuthProvider({children}:{children:React.ReactNode}){const [session,setSession]=useState<Session|null>(null);const [profile,setProfile]=useState<Record<string,unknown>|null>(null);const [organization,setOrganization]=useState<Record<string,unknown>|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{const supabase=createClient();let active=true;const loadProfile=async(nextSession:Session|null)=>{if(!nextSession){setProfile(null);setOrganization(null);setLoading(false);return}setLoading(true);const result=await getCurrentProfile(supabase);if(!active)return;const nextProfile=result.profile as (Record<string,unknown>&{organization_id?:string|null})|null;setProfile(nextProfile);if(nextProfile?.organization_id){const {data}=await supabase.from('organizations').select('id, name, created_at, updated_at').eq('id',nextProfile.organization_id).maybeSingle();if(active)setOrganization(data as Record<string,unknown>|null)}else setOrganization(null);setLoading(false)};supabase.auth.getSession().then(({data})=>{if(active){setSession(data.session);void loadProfile(data.session)}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);void loadProfile(next)});return()=>{active=false;subscription.unsubscribe()}},[]);const signOut=async()=>{await createClient().auth.signOut();setSession(null);setProfile(null);setOrganization(null);window.location.assign('/login')};const value=useMemo(()=>({session,user:session?.user??null,profile,organization,role:String(profile?.role??'Viewer'),loading,signOut}),[session,profile,organization,loading]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export const useAuth=()=>useContext(AuthContext);
