'use client'

import Link from 'next/link'
import { AlertTriangle, ArrowRight, BarChart3, Brain, CheckCircle2, Database, FileText, Lightbulb, Search, ShieldAlert, Target } from 'lucide-react'

const areas = ['Finance', 'Sales', 'Marketing', 'Customers', 'Operations', 'Product', 'Workforce', 'Risk']

function EmptyPanel({ icon: Icon, title, children, action }: { icon: typeof Brain; title: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="rounded-2xl border border-border/70 bg-card p-5"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon size={19} /></span><div className="min-w-0"><h2 className="font-semibold tracking-tight">{title}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{children}</p>{action ? <div className="mt-4">{action}</div> : null}</div></div></section>
}

export function BusinessAnalystWorkspace({ mode = 'dashboard' }: { mode?: 'dashboard' | 'brain' | 'inspector' | 'forecast' | 'brief' | 'reports' | 'data' }) {
  if (mode === 'brain') return <main className="min-h-screen bg-background px-5 py-8"><div className="mx-auto max-w-7xl"><Header eyebrow="Company Brain" title="Your company context, in one place." description="The intelligence foundation for your goals, knowledge, departments, data, and decisions." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><EmptyPanel icon={Target} title="Company profile">Configure your identity, business model, customers, products, and operating regions.</EmptyPanel><EmptyPanel icon={Target} title="Objectives">Define structured goals with targets, owners, deadlines, and status.</EmptyPanel><EmptyPanel icon={Database} title="Data coverage" action={<Link className="inline-flex items-center gap-2 text-sm font-medium text-primary" href="/brain/data-sources">Connect data <ArrowRight size={15} /></Link>}>No business sources connected yet. Connect a source to unlock grounded analysis.</EmptyPanel></div><div className="mt-4 rounded-2xl border border-border/70 bg-card p-5"><h2 className="font-semibold">Intelligence map</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Company', 'Knowledge', 'Data', 'KPIs', 'Insights', 'Recommendations', 'Agents', 'Workflows'].map((item) => <div className="rounded-xl border border-border/60 bg-muted/30 p-4 text-sm" key={item}><span className="text-muted-foreground">Layer</span><p className="mt-1 font-medium">{item}</p><p className="mt-2 text-xs text-muted-foreground">Ready for configuration</p></div>)}</div></div></div></main>
  if (mode === 'inspector') return <main className="min-h-screen bg-background px-5 py-8"><div className="mx-auto max-w-7xl"><Header eyebrow="Business Analyst / Inspector" title="Inspect the business with evidence." description="Run grounded analysis across the data currently connected to your Company Brain." /><div className="rounded-2xl border border-primary/30 bg-primary/5 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Ready when your data is connected</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">The inspector will separate facts, inferences, and recommendations. It will not invent metrics.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground" type="button"><Search size={16} /> Run full business inspection</button></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><EmptyPanel icon={AlertTriangle} title="Critical issues">No findings until business data is available.</EmptyPanel><EmptyPanel icon={ShieldAlert} title="Risks">Risk indicators will be evaluated from connected evidence.</EmptyPanel><EmptyPanel icon={CheckCircle2} title="Strengths">Verified improvements will appear here.</EmptyPanel><EmptyPanel icon={Lightbulb} title="Opportunities">Recommendations will include evidence, confidence, and effort.</EmptyPanel></div></div></main>
  if (mode === 'forecast') return <main className="min-h-screen bg-background px-5 py-8"><div className="mx-auto max-w-7xl"><Header eyebrow="Business Analyst / Forecast" title="Plan forward with transparent assumptions." description="Forecasting foundations for revenue, expenses, cash flow, customers, sales, and demand." /><div className="grid gap-4 md:grid-cols-2"><EmptyPanel icon={BarChart3} title="No forecast available">Connect time-series business data to generate a forecast with inputs, method, horizon, assumptions, and confidence range.</EmptyPanel><EmptyPanel icon={Target} title="Scenario analysis">What-if estimates will be clearly labeled and will never be presented as actual results.</EmptyPanel></div></div></main>
  if (mode === 'brief' || mode === 'reports') return <main className="min-h-screen bg-background px-5 py-8"><div className="mx-auto max-w-7xl"><Header eyebrow={mode === 'brief' ? 'Executive Brief' : 'Reports'} title={mode === 'brief' ? 'A concise briefing for management.' : 'Reports grounded in your business data.'} description="No reports have been generated because there is not enough connected business data yet." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{(mode === 'brief' ? ['What happened', 'Why it matters', 'Recommended actions'] : ['Daily Business Brief', 'Weekly Business Review', 'Monthly Business Review', 'Executive Report', 'KPI Report', 'Risk Report']).map((title) => <EmptyPanel icon={FileText} title={title} key={title}>Connect data to make this section evidence-based.</EmptyPanel>)}</div></div></main>
  if (mode === 'data') return <main className="min-h-screen bg-background px-5 py-8"><div className="mx-auto max-w-7xl"><Header eyebrow="Company Brain / Data Sources" title="Connect the systems that power your decisions." description="This foundation never claims a source is connected until it has been configured and verified." /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['CSV', 'Excel', 'Google Sheets', 'PostgreSQL', 'Supabase', 'CRM', 'Accounting', 'Analytics'].map((source) => <div className="rounded-2xl border border-border/70 bg-card p-5" key={source}><Database className="text-muted-foreground" size={19} /><h2 className="mt-4 font-medium">{source}</h2><p className="mt-1 text-sm text-muted-foreground">Not connected</p></div>)}</div></div></main>
  return <main className="min-h-screen bg-background px-5 py-8"><div className="mx-auto max-w-7xl"><Header eyebrow="Business Analyst" title="Understand what is happening in your business." description="Evidence-based analysis starts with connected data. Your analyst is ready for its first source." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><EmptyPanel icon={Brain} title="Business Health">Insufficient business data. Connect KPIs across at least one business area before calculating a score.</EmptyPanel><EmptyPanel icon={BarChart3} title="KPI overview">No KPI values are available yet. Add or connect a source to begin tracking performance.</EmptyPanel><EmptyPanel icon={Lightbulb} title="Recommendations">Recommendations appear only when supported by evidence and data quality.</EmptyPanel></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><EmptyPanel icon={Database} title="Data quality">No data coverage to assess. Missing, stale, or inconsistent periods will be flagged before analysis.</EmptyPanel><EmptyPanel icon={Target} title="Next best action" action={<Link href="/brain/data-sources" className="inline-flex items-center gap-2 text-sm font-medium text-primary">Connect your first source <ArrowRight size={15} /></Link>}>Your Company Brain is ready. Bring in one trusted source to start.</EmptyPanel></div><div className="mt-6 flex flex-wrap gap-2">{areas.map((area) => <span className="rounded-full border border-border/70 px-3 py-1.5 text-xs text-muted-foreground" key={area}>{area}</span>)}</div></div></main>
}

function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{eyebrow}</p><h1 className="mt-3 max-w-3xl text-balance text-3xl font-semibold tracking-tight md:text-5xl">{title}</h1><p className="mt-4 max-w-2xl text-pretty leading-7 text-muted-foreground">{description}</p></header> }

export function BusinessAnalystNav() { return <nav aria-label="Business intelligence" className="flex flex-wrap gap-2"><Link href="/brain">Company Brain</Link><Link href="/business-analyst">Analyst</Link><Link href="/business-analyst/inspector">Inspector</Link><Link href="/business-analyst/forecast">Forecast</Link><Link href="/reports">Reports</Link></nav> }
