'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowRight, BarChart3, Brain, Database, FileText, Lightbulb, Target } from 'lucide-react'
const areas=['Finance','Sales','Marketing','Customers','Operations','Product','Workforce','Risk']
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-border/70 bg-card p-5"><h2 className="font-semibold tracking-tight">{title}</h2><div className="mt-3 text-sm leading-6 text-muted-foreground">{children}</div></section>}
export function BusinessAnalystWorkspace({mode='dashboard'}:{mode?:string}){
 const [data,setData]=useState<any>(null); const [error,setError]=useState(''); useEffect(()=>{if(mode==='dashboard') fetch('/api/business/analysis').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}).catch(e=>setError(e.message))},[mode])
 if(mode!=='dashboard') return <main className="min-h-screen bg-background px-5 py-8"><div className="mx-auto max-w-7xl"><header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Business Analyst</p><h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-5xl">Evidence before conclusions.</h1><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">This view remains grounded in verified organization data.</p></header><Panel title="Insufficient data">Connect and confirm a source mapping to begin analysis.</Panel></div></main>
 if(error)return <main className="p-6"><Panel title="Unable to load analysis">{error}</Panel></main>
 if(!data)return <main className="p-6"><Panel title="Loading analysis">Checking verified business evidence…</Panel></main>
 const hasData=data.kpis.length>0
 return <main className="min-h-screen bg-background px-5 py-8"><div className="mx-auto max-w-7xl"><header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Business Analyst</p><h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-5xl">Understand what is happening in your business.</h1><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">Only confirmed KPI mappings and organization-scoped records appear here.</p></header>{!hasData?<div className="grid gap-4 md:grid-cols-2"><Panel title="Insufficient business data">Connect a source and confirm at least one KPI mapping before calculating a score.</Panel><Panel title="Next best action"><Link href="/brain/data-sources" className="inline-flex items-center gap-2 text-primary">Connect your first source <ArrowRight size={15}/></Link></Panel></div>:<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Panel title="Business Health"><strong className="text-3xl text-foreground">{data.health ?? '—'}</strong><p>Based on {data.kpis.length} verified KPI{data.kpis.length===1?'':'s'}.</p></Panel><Panel title="Data coverage"><strong className="text-3xl text-foreground">{data.quality}%</strong><p>{data.areas.length} KPI areas covered.</p></Panel><Panel title="KPI overview"><strong className="text-3xl text-foreground">{data.kpis.length}</strong><p>Confirmed values available.</p></Panel><Panel title="Next best action">{data.nextAction}</Panel></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="KPI overview"><div className="space-y-3">{data.kpis.map((k:any)=><div className="flex items-center justify-between gap-4 border-b border-border/60 pb-3" key={k.id}><div><p className="font-medium text-foreground">{k.name}</p><p className="text-xs">{k.source} · {k.period} · {k.status}</p></div><strong className="text-foreground">{k.value} {k.unit}</strong></div>)}</div></Panel><Panel title="Evidence-based recommendations">{data.recommendations.length?<div className="space-y-4">{data.recommendations.map((r:any)=><div key={r.title}><p className="font-medium text-foreground">{r.title}</p><p>{r.problem}</p><p className="mt-1 text-foreground">{r.recommended_action}</p><p className="text-xs">Confidence {Math.round(r.confidence*100)}%</p></div>)}</div>:'Recommendations appear only when supported by comparable KPI evidence.'}</Panel><Panel title="Data quality">{data.quality}% verified KPI coverage. Freshness and completeness warnings remain attached to each imported source.</Panel><Panel title="Business areas covered"><div className="flex flex-wrap gap-2">{areas.map(a=><span key={a} className={`rounded-full border px-3 py-1.5 text-xs ${data.areas.includes(a)?'border-primary text-primary':'border-border/70'}`}>{a}</span>)}</div></Panel></div></>}</div></main>
}
export function BusinessAnalystNav(){return <nav aria-label="Business intelligence" className="flex flex-wrap gap-2"><Link href="/brain">Company Brain</Link><Link href="/business-analyst">Analyst</Link><Link href="/brain/data-sources">Data Sources</Link><Link href="/reports">Reports</Link></nav>}
