'use client'

import Link from 'next/link'
import useSWR from 'swr'
import { ArrowRight, Bot, Brain, CheckCircle2, Clock3, Film, GitBranch, Image as ImageIcon, MessageSquare, Plus, Sparkles, Workflow, Zap } from 'lucide-react'
import { Card, PageHeader, Status } from '@/components/ui'
import { workspaceFetcher } from '@/lib/repositories/workspace'
import { CommandCenter } from '@/components/command-center'

const productLinkClass = 'flex min-h-11 items-center justify-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-medium transition hover:border-primary hover:text-primary'

function LegacyAIWorkspacePage() {
  const { data, error, isLoading } = useSWR('workspace', workspaceFetcher)
  const agents = data?.agents ?? []
  const workflows = data?.workflows ?? []
  const documents = data?.documents ?? []
  const activity = data?.activity ?? []

  return <div className="space-y-6">
    <PageHeader eyebrow="Command center" title="AI Workspace" subtitle="Your central command center for working with AI across your company." action={<div className="flex flex-wrap gap-2"><Link href="/brain" className="flex min-h-11 items-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-medium"><MessageSquare size={16}/> New AI Session</Link><Link href="/agents" className="flex min-h-11 items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground"><Plus size={16}/> Start Task</Link></div>}/>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <Card className="min-h-[430px] overflow-hidden border-primary/20 bg-gradient-to-br from-primary/10 via-card to-card">
        <div className="flex items-start gap-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Brain size={21}/></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">AI command surface</p><h2 className="mt-2 text-xl font-semibold">What do you want to move forward?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Start with a question, a business task, or a team decision. Company Brain is the grounded context layer for your next AI session.</p></div></div>
        <div className="mt-8 flex min-h-28 flex-col justify-between rounded-xl border bg-background/50 p-3"><textarea aria-label="AI task prompt" placeholder="Ask, analyze, draft, or plan something for your company..." className="min-h-16 resize-none bg-transparent p-2 text-sm outline-none"/><div className="flex justify-end"><Link href="/brain" className="flex min-h-11 items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Open AI session <ArrowRight size={15}/></Link></div></div>
        <div className="mt-5 grid gap-2 sm:grid-cols-2"><QuickAction href="/business-analyst" icon={<Zap size={15}/>} label="Ask the Business Analyst"/><QuickAction href="/brain" icon={<Brain size={15}/>} label="Ask Company Brain"/><QuickAction href="/studio" icon={<Film size={15}/>} label="Create Media"/><QuickAction href="/workflows" icon={<Workflow size={15}/>} label="Create Workflow"/></div>
      </Card>
      <Card><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Workspace context</p><h2 className="mt-2 text-lg font-semibold">Your operating layer</h2></div><Sparkles size={18} className="text-primary"/></div><div className="mt-6 grid grid-cols-2 gap-3">{[['Agents', agents.length, '/agents'], ['Workflows', workflows.length, '/workflows'], ['Knowledge', documents.length, '/knowledge'], ['Activity', activity.length, '/activity']].map(([label, value, href]) => <Link key={String(label)} href={String(href)} className="rounded-xl border bg-muted/20 p-4 transition hover:border-primary"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{isLoading ? '—' : value}</p></Link>)}</div>{error && <p className="mt-4 text-sm text-rose-400">Workspace context is unavailable right now.</p>}<p className="mt-6 text-sm leading-6 text-muted-foreground">Counts reflect organization-scoped records only. Empty areas stay empty until your team creates real work.</p></Card>
    </div>
    <Card><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Recent work</p><h2 className="mt-2 text-lg font-semibold">Your AI work will appear here</h2><p className="mt-1 text-sm text-muted-foreground">{activity.length ? 'Recent organization activity is available in Activity.' : 'No AI work yet. Start your first AI session to begin working with your company intelligence.'}</p></div><Link href="/activity" className={productLinkClass}>View activity <ArrowRight size={15}/></Link></div></Card>
  </div>
}

export function AIWorkspacePage() { return <CommandCenter /> }

function QuickAction({ href, icon, label }: { href: string; icon: React.ReactNode; label: string }) { return <Link href={href} className="flex min-h-11 items-center gap-2 rounded-lg border px-3 py-2.5 text-xs text-muted-foreground transition hover:border-primary hover:text-primary">{icon}{label}</Link> }

export function MediaGenerationPage() { return <div className="space-y-6"><PageHeader eyebrow="Creative production" title="AI Media Generation" subtitle="Create images, video, audio and other AI-powered media for your business." action={<Link href="/studio/history" className={productLinkClass}><Clock3 size={16}/> Generation history</Link>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MediaMode icon={<Film size={19}/>} title="Video" description="Prompt-to-video production" active/><MediaMode icon={<ImageIcon size={19}/>} title="Image" description="Prompt-to-image production" active/><MediaMode icon={<MessageSquare size={19}/>} title="Audio" description="Voice and audio workflows"/><MediaMode icon={<Sparkles size={19}/>} title="Content" description="Structured content generation"/></div><Card className="border-primary/20 bg-gradient-to-br from-primary/10 via-card to-card"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Production studio</p><h2 className="mt-2 text-2xl font-semibold">Create a new piece of media</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Use the existing AI Studio generation engine to queue supported image and video jobs. Outputs and processing states remain visible in Generation History.</p></div><Link href="/studio" className="flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground">Open creation studio <ArrowRight size={15}/></Link></div></Card><Card><div className="flex flex-col items-center justify-center gap-3 py-12 text-center"><Film size={26} className="text-primary"/><h2 className="font-medium">No generations yet</h2><p className="max-w-md text-sm text-muted-foreground">Create your first piece of AI media. Real generation history will appear here once a job is submitted.</p><Link href="/studio" className="flex min-h-11 items-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-medium hover:border-primary hover:text-primary">Create media <ArrowRight size={15}/></Link></div></Card></div> }

function MediaMode({ icon, title, description, active }: { icon: React.ReactNode; title: string; description: string; active?: boolean }) { return <div className={`rounded-xl border p-5 ${active ? 'border-primary/40 bg-primary/5' : 'opacity-70'}`}><div className="flex items-center justify-between"><span className={active ? 'text-primary' : 'text-muted-foreground'}>{icon}</span><Status value={active ? 'Draft' : 'Paused'}/></div><h2 className="mt-5 font-medium">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p><p className="mt-4 text-xs text-muted-foreground">{active ? 'Available in AI Studio' : 'Coming soon'}</p></div> }

export function AutomationPage() { const { data, error, isLoading } = useSWR('workspace', workspaceFetcher); const workflows = data?.workflows ?? []; return <div className="space-y-6"><PageHeader eyebrow="Operations layer" title="AI Automation" subtitle="Connect systems, trigger workflows and automate repetitive business processes." action={<Link href="/workflows" className="flex min-h-11 items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground"><Plus size={16}/> Create Workflow</Link>}/><div className="grid gap-4 sm:grid-cols-3"><AutomationStat label="Workflows" value={isLoading ? '—' : String(workflows.length)} icon={<Workflow size={18}/>}/><AutomationStat label="Executions" value="—" icon={<GitBranch size={18}/>} note="No execution source connected"/><AutomationStat label="Automation engine" value="n8n" icon={<Zap size={18}/>} note="Server-side integration"/></div><Card><div className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Operations control</p><h2 className="mt-2 text-lg font-semibold">Workflows</h2><p className="mt-1 text-sm text-muted-foreground">Real organization workflows and their current status.</p></div><Link href="/integrations/n8n" className={productLinkClass}>Configure n8n <ArrowRight size={15}/></Link></div>{error ? <p className="py-12 text-center text-sm text-rose-400">Workflows could not be loaded.</p> : workflows.length ? <div className="divide-y">{workflows.map(workflow => <div key={workflow.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-medium">{workflow.name}</h3><p className="mt-1 text-sm text-muted-foreground">{workflow.description || 'No workflow description provided.'}</p></div><div className="flex items-center gap-3"><Status value={workflow.status}/><span className="text-xs text-muted-foreground">Updated {new Date(workflow.updated_at).toLocaleDateString()}</span></div></div>)}</div> : <div className="flex flex-col items-center justify-center gap-3 py-14 text-center"><Workflow size={26} className="text-primary"/><h2 className="font-medium">No workflows yet</h2><p className="max-w-md text-sm text-muted-foreground">Create a workflow when your organization is ready. Executions will appear here only when the backend records them.</p><Link href="/workflows" className={productLinkClass}>Open workflow area <ArrowRight size={15}/></Link></div>}</Card></div> }

function AutomationStat({ label, value, icon, note }: { label: string; value: string; icon: React.ReactNode; note?: string }) { return <Card><div className="flex items-center justify-between text-primary">{icon}<span className="text-xs text-muted-foreground">{label}</span></div><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note ?? 'Organization-scoped data'}</p></Card> }

export function AgentsOverviewIntro() { return <Card className="mb-6 border-primary/20 bg-primary/5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">AI workforce</p><h2 className="mt-2 text-lg font-semibold">Specialized AI workers for your company</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-muted-foreground">Agents have defined responsibilities, capabilities, and organization-scoped context. Create or manage real agents from this workspace.</p></div><Link href="/workspace" className={productLinkClass}>Back to workspace <ArrowRight size={15}/></Link></div></Card> }
