import Link from 'next/link'; import {ArrowUpRight, MoreHorizontal, Activity as ActivityIcon, Bot, Workflow, FileText, CheckCircle2, Clock3, AlertTriangle} from 'lucide-react'; import {Agent,Department,Activity} from '@/lib/data';
export function PageHeader({eyebrow,title,subtitle,action}:{eyebrow?:string;title:string;subtitle:string;action?:React.ReactNode}){return <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 text-xs font-medium uppercase tracking-[.18em] text-primary">{eyebrow||'Command center'}</div><h1 className="text-3xl font-semibold tracking-tight text-balance md:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{subtitle}</p></div>{action}</div>}
export function Card({children,className='' }:{children:React.ReactNode;className?:string}){return <section className={`glass rounded-xl border p-5 ${className}`}>{children}</section>}
export function KpiCard({label,value,change,icon}:{label:string;value:string;change:string;icon:React.ReactNode}){return <Card><div className="flex items-start justify-between"><div className="rounded-lg bg-primary/10 p-2.5 text-primary">{icon}</div><span className="text-xs text-primary">{change}</span></div><div className="mt-5 text-3xl font-semibold tracking-tight">{value}</div><div className="mt-1 text-sm text-muted-foreground">{label}</div></Card>}
export function Status({value}:{value:string}){const good=value==='Running'||value==='Indexed'||value==='Success'||value==='Operational'; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-xs ${good?'bg-primary/10 text-primary':'bg-accent/10 text-accent'}`}><span className="size-1.5 rounded-full bg-current"/>{value}</span>}
export function DepartmentCard({d}:{d:Department}){return <Card className="transition hover:-translate-y-0.5 hover:border-primary/40"><div className="flex items-start justify-between"><div className="flex size-10 items-center justify-center rounded-lg bg-muted text-lg text-primary">{d.icon}</div><Status value={d.status}/></div><h3 className="mt-4 font-medium">{d.name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-muted-foreground">{d.description}</p><div className="mt-4 flex items-end justify-between border-t pt-4"><div><span className="text-lg font-semibold">{d.agents}</span><span className="ml-1 text-xs text-muted-foreground">agents</span></div><Link href={`/departments/${d.id}`} className="flex items-center gap-1 text-xs text-primary hover:underline">View <ArrowUpRight size={13}/></Link></div></Card>}
export function AgentCard({agent}:{agent:Agent}){return <Card className="transition hover:border-primary/40"><div className="flex items-start justify-between"><div className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><Bot size={20}/></div><button className="rounded p-1 text-muted-foreground hover:bg-muted" aria-label="Agent actions"><MoreHorizontal size={18}/></button></div><h3 className="mt-4 font-medium"><Link href={`/agents/${agent.id}`} className="hover:text-primary">{agent.name}</Link></h3><div className="mt-1 text-xs text-primary">{agent.department}</div><p className="mt-3 min-h-10 text-xs leading-5 text-muted-foreground">{agent.purpose}</p><div className="mt-4 flex items-center justify-between border-t pt-4"><Status value={agent.status}/><span className="text-xs text-muted-foreground">{agent.lastActivity}</span></div></Card>}
export function ActivityTimeline({items}:{items:Activity[]}){return <div className="flex flex-col">{items.map((item,i)=><div key={i} className="flex gap-3 border-b py-4 last:border-0"><div className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-full bg-muted text-primary"><ActivityIcon size={15}/></div><div className="min-w-0 flex-1"><div className="text-sm"><span className="font-medium">{item.actor}</span> <span className="text-muted-foreground">{item.action}</span></div><div className="mt-1 text-xs text-muted-foreground">{item.department} · {item.time}</div></div><Status value={item.status}/></div>)}</div>}
export const icons={ActivityIcon,Bot,Workflow,FileText,CheckCircle2,Clock3,AlertTriangle};
