export type Status='Running'|'Paused'|'Draft'|'Needs Attention'|'Indexed'|'Processing'|'Failed';
export type Role='Owner'|'Admin'|'Manager'|'Member'|'Viewer';
export interface Department { id:string; name:string; description:string; agents:number; active:number; icon:string; status:string }
export interface Agent { id:string; name:string; department:string; purpose:string; status:Status; model:string; lastActivity:string; tasks:number }
export interface Activity { actor:string; action:string; department:string; status:string; time:string }
const departmentRows: [string,string,string,number,number,string,string][]=[['sales','Sales','Pipeline intelligence and revenue systems',20,14,'↗','Operational'],['marketing','Marketing','Demand generation and brand systems',22,16,'✦','Operational'],['operations','Operations','Process automation and execution',18,12,'◈','Operational'],['finance','Finance','Financial planning and controls',19,11,'◒','Operational'],['customer-success','Customer Success','Retention and customer intelligence',18,13,'♡','Operational'],['intelligence','Intelligence','Market and business intelligence',20,15,'⌁','Operational'],['engineering','Engineering','Product and technical systems',20,16,'⌘','Operational']];
export const departments:Department[]=departmentRows.map(([id,name,description,agentCount,active,icon,status])=>({id,name,description,agents:agentCount,active,icon,status}));
const names=['Lead Researcher','Sales Outreach Agent','Proposal Writer','Customer Support Agent','Market Intelligence Agent','Content Strategist','Financial Analyst','Code Assistant','Operations Coordinator','CEO Assistant'];
export const agents:Agent[]=Array.from({length:30},(_,i)=>({id:`agent-${i}`,name:names[i%names.length],department:departments[i%7].name,purpose:['Research, qualify, and enrich target accounts','Build context-aware outreach sequences','Draft high-converting proposals','Resolve support requests with company context'][i%4],status:(['Running','Running','Paused','Draft','Needs Attention'] as Status[])[i%5],model:['GPT-4o','Claude 3.5 Sonnet','Gemini 1.5 Pro'][i%3],lastActivity:`${i+1}h ago`,tasks:42+i*7}));
export const activity:Activity[]=[['AI Agent','Completed lead research','Sales','Success','2 min ago'],['User','Uploaded company document','Company Brain','Success','18 min ago'],['Workflow','Completed customer onboarding','Operations','Success','42 min ago'],['AI Agent','Generated campaign brief','Marketing','Success','1 hr ago'],['Workflow','Invoice processing needs review','Finance','Attention','2 hrs ago']].map(x=>({actor:x[0],action:x[1],department:x[2],status:x[3],time:x[4]}));
export const nav=[['Dashboard','/dashboard','⌂'],['AI Studio','/studio','✹'],['History','/studio/history','◷'],['Credits','/studio/credits','◈'],['Company Brain','/brain','◉'],['Business Analyst','/business-analyst','▥'],['AI Agents','/agents','✦'],['Departments','/departments','◈'],['Workflows','/workflows','⌁'],['Knowledge','/knowledge','▤'],['Analytics','/analytics','▥'],['Activity','/activity','◷'],['Integrations','/integrations','⊞'],['Settings','/settings','⚙'],['About','/about','◌']];
export const modelTypes=['GPT-4o','Claude 3.5 Sonnet','Gemini 1.5 Pro'];
