export type IntegrationStatus = 'not-configured' | 'setup-required' | 'connected' | 'connection-error' | 'coming-soon'

export type IntegrationProvider = {
  id: string
  name: string
  category: string
  description: string
  icon: string
  connectionMethod: string
  envKeys: string[]
  setupInstructions: string[]
  capabilities: string[]
  plannedCapabilities: string[]
  securityNotes: string[]
  usedIn: { name: string; state: 'Available now' | 'Requires configuration' | 'Planned'; href?: string }[]
  status: IntegrationStatus
}

export const integrations: IntegrationProvider[] = [
  { id: 'openai', name: 'OpenAI', category: 'AI Provider', description: 'Server-side models for AI Studio, agent intelligence, and grounded company analysis.', icon: 'sparkles', connectionMethod: 'Environment variable', envKeys: ['OPENAI_API_KEY', 'OPENAI_MODEL'], setupInstructions: ['Add OPENAI_API_KEY to the server environment.', 'Set OPENAI_MODEL when you need to select a supported model.', 'Keep both values server-side; browser code never receives them.'], capabilities: ['AI generation', 'Agent intelligence', 'Business analysis', 'AI Studio'], plannedCapabilities: [], securityNotes: ['Keys are only read by server routes.', 'Never commit provider credentials to GitHub.'], usedIn: [{ name: 'AI Studio', state: 'Available now', href: '/studio' }, { name: 'Agents', state: 'Available now', href: '/agents' }, { name: 'Company Brain', state: 'Requires configuration', href: '/brain' }], status: 'setup-required' },
  { id: 'anthropic', name: 'Anthropic', category: 'AI Provider', description: 'An optional server-side provider for Claude model workloads.', icon: 'brain', connectionMethod: 'Environment variable', envKeys: ['ANTHROPIC_API_KEY'], setupInstructions: ['Add ANTHROPIC_API_KEY to the server environment.', 'Choose the model in the server provider configuration.', 'The key must never be sent to the browser.'], capabilities: ['Claude model access'], plannedCapabilities: ['Agent routing'], securityNotes: ['Use least-privilege provider credentials.', 'Rotate keys through your deployment environment.'], usedIn: [{ name: 'AI Workspace', state: 'Requires configuration' }, { name: 'Agents', state: 'Planned' }], status: 'setup-required' },
  { id: 'gemini', name: 'Google Gemini', category: 'AI Provider', description: 'Google Gemini models for future multi-provider intelligence workflows.', icon: 'cpu', connectionMethod: 'Environment variable', envKeys: ['GOOGLE_GENERATIVE_AI_API_KEY'], setupInstructions: ['Add GOOGLE_GENERATIVE_AI_API_KEY to the server environment.', 'Configure the selected Gemini model on the server.', 'Do not paste keys into client-side forms.'], capabilities: ['Gemini model access'], plannedCapabilities: ['Business analysis', 'Agent routing'], securityNotes: ['Credentials remain server-side.', 'Use OAuth or managed identity where your deployment supports it.'], usedIn: [{ name: 'AI Workspace', state: 'Requires configuration' }, { name: 'Company Brain', state: 'Planned' }], status: 'setup-required' },
  { id: 'n8n', name: 'n8n', category: 'Automation', description: 'Connect n8n webhooks and workflows when an automation backend is configured.', icon: 'workflow', connectionMethod: 'Base URL and webhook secret', envKeys: ['N8N_BASE_URL', 'N8N_WEBHOOK_SECRET'], setupInstructions: ['Provide an n8n base or webhook URL on the server.', 'Configure webhook authentication and signature verification.', 'Map events to a defined workflow contract before enabling triggers.'], capabilities: ['Workflow automation', 'Webhooks'], plannedCapabilities: ['External workflow execution', 'Inbound automation events'], securityNotes: ['Verify webhook signatures before accepting events.', 'Do not expose webhook secrets in the UI.'], usedIn: [{ name: 'Workflows', state: 'Requires configuration', href: '/workflows' }, { name: 'Agents', state: 'Planned', href: '/agents' }], status: 'coming-soon' },
  { id: 'github', name: 'GitHub', category: 'Developer', description: 'Repository and developer automation connectivity for engineering workflows.', icon: 'github', connectionMethod: 'OAuth app or GitHub App', envKeys: ['GITHUB_CLIENT_ID', 'GITHUB_CLIENT_SECRET'], setupInstructions: ['Register an OAuth app or GitHub App.', 'Set the callback URL for the deployed environment.', 'Request only repository scopes required by the enabled workflow.'], capabilities: ['Repository access'], plannedCapabilities: ['Development automation', 'Code workflow integrations'], securityNotes: ['Prefer GitHub Apps and narrow repository permissions.', 'OAuth secrets stay server-side.'], usedIn: [{ name: 'Engineering', state: 'Planned' }, { name: 'Workflows', state: 'Planned', href: '/workflows' }], status: 'coming-soon' },
  { id: 'supabase', name: 'Supabase', category: 'Infrastructure', description: 'The core database, authentication, and backend already used by TechUnified.', icon: 'database', connectionMethod: 'Existing project environment', envKeys: ['NEXT_PUBLIC_SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'], setupInstructions: ['Supabase is already part of the core application architecture.', 'Project configuration is read from the existing server environment.', 'Service-role credentials must remain server-side and are never entered here.'], capabilities: ['Database', 'Authentication', 'Row-level security'], plannedCapabilities: [], securityNotes: ['RLS remains the source of truth for organization isolation.', 'Service-role access is restricted to trusted server code.'], usedIn: [{ name: 'Core application', state: 'Available now' }, { name: 'Company Brain', state: 'Available now', href: '/brain' }], status: 'connected' },
  { id: 'whatsapp', name: 'WhatsApp', category: 'Communication', description: 'Meta WhatsApp Business Platform connectivity for customer messaging and notifications.', icon: 'message-circle', connectionMethod: 'Meta Business Platform', envKeys: ['WHATSAPP_ACCESS_TOKEN', 'WHATSAPP_PHONE_NUMBER_ID'], setupInstructions: ['Create or connect a Meta Business account.', 'Register a phone number and obtain its Phone Number ID.', 'Configure access tokens and a verified webhook endpoint.'], capabilities: ['Customer messaging', 'Notifications'], plannedCapabilities: ['Business communication'], securityNotes: ['Use Meta webhook verification and token rotation.', 'A normal WhatsApp link is not a Business API connection.'], usedIn: [{ name: 'Customer Success', state: 'Planned' }, { name: 'Notifications', state: 'Planned' }], status: 'coming-soon' },
  { id: 'gmail', name: 'Gmail', category: 'Communication', description: 'Google OAuth and Gmail API connectivity for email automation and business communication.', icon: 'mail', connectionMethod: 'Google OAuth', envKeys: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'], setupInstructions: ['Create a Google OAuth application.', 'Configure the exact production redirect URI.', 'Request only the Gmail scopes required by the selected capability.'], capabilities: ['Email automation'], plannedCapabilities: ['Notifications', 'Business communication'], securityNotes: ['Use OAuth consent and revocable user grants.', 'Store refresh tokens only in protected server storage.'], usedIn: [{ name: 'Notifications', state: 'Planned' }, { name: 'Customer Success', state: 'Planned' }], status: 'coming-soon' },
  { id: 'slack', name: 'Slack', category: 'Communication', description: 'Slack workspace authorization for notifications, messaging, and workflow events.', icon: 'hash', connectionMethod: 'Slack OAuth', envKeys: ['SLACK_CLIENT_ID', 'SLACK_CLIENT_SECRET'], setupInstructions: ['Create a Slack app and configure OAuth redirect URLs.', 'Request the minimum bot and workspace scopes.', 'Authorize the intended workspace before enabling events.'], capabilities: ['Notifications', 'Team communication'], plannedCapabilities: ['Workflow events'], securityNotes: ['Verify Slack request signatures for inbound events.', 'Keep client secrets on the server.'], usedIn: [{ name: 'Notifications', state: 'Planned' }, { name: 'Workflows', state: 'Planned', href: '/workflows' }], status: 'coming-soon' },
  { id: 'stripe', name: 'Stripe', category: 'Payments', description: 'Payment and event connectivity for future finance and billing workflows.', icon: 'credit-card', connectionMethod: 'API keys and signed webhooks', envKeys: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'], setupInstructions: ['Create server-side Stripe API credentials.', 'Configure the webhook endpoint and signing secret.', 'Use the publishable key only in approved client payment flows.'], capabilities: ['Payment events'], plannedCapabilities: ['Transaction data', 'Payment automation'], securityNotes: ['Verify webhook signatures.', 'Never expose secret keys or log payment credentials.'], usedIn: [{ name: 'Finance', state: 'Planned' }, { name: 'Workflows', state: 'Planned', href: '/workflows' }], status: 'coming-soon' },
  { id: 'paystack', name: 'Paystack', category: 'Payments', description: 'Paystack payment events and transaction verification for future finance workflows.', icon: 'wallet', connectionMethod: 'Public/secret keys and webhooks', envKeys: ['PAYSTACK_SECRET_KEY'], setupInstructions: ['Configure the public key only for approved client flows.', 'Store PAYSTACK_SECRET_KEY on the server.', 'Verify webhook signatures and transaction status server-side.'], capabilities: ['Payment capabilities'], plannedCapabilities: ['Payment events', 'Transaction data'], securityNotes: ['Recompute and verify transaction state on the server.', 'Never commit secret keys.'], usedIn: [{ name: 'Finance', state: 'Planned' }], status: 'coming-soon' },
  { id: 'flutterwave', name: 'Flutterwave', category: 'Payments', description: 'Flutterwave transaction and webhook connectivity for future payment operations.', icon: 'landmark', connectionMethod: 'Public/secret keys and webhooks', envKeys: ['FLUTTERWAVE_SECRET_KEY'], setupInstructions: ['Configure public and secret keys in the server environment.', 'Set up signed webhook delivery.', 'Verify every transaction before recording a business event.'], capabilities: ['Payment capabilities'], plannedCapabilities: ['Payment events', 'Transaction verification'], securityNotes: ['Keep secret keys server-side.', 'Validate webhook signatures and transaction references.'], usedIn: [{ name: 'Finance', state: 'Planned' }], status: 'coming-soon' },
]

export function getIntegration(id: string) { return integrations.find((integration) => integration.id === id) }
export function getIntegrationStatus(id: string, available: Record<string, boolean>): IntegrationStatus {
  const provider = getIntegration(id)
  if (!provider) return 'connection-error'
  if (provider.id === 'supabase') return available.supabase ? 'connected' : 'setup-required'
  if (provider.status === 'coming-soon') return 'coming-soon'
  return provider.envKeys.every((key) => available[key]) ? 'connected' : 'setup-required'
}

export const statusLabels: Record<IntegrationStatus, string> = { 'not-configured': 'Not configured', 'setup-required': 'Setup required', connected: 'Connected', 'connection-error': 'Connection error', 'coming-soon': 'Coming soon' }
export const statusStyles: Record<IntegrationStatus, string> = { 'not-configured': 'border-border bg-muted text-muted-foreground', 'setup-required': 'border-amber-500/30 bg-amber-500/10 text-amber-300', connected: 'border-primary/30 bg-primary/10 text-primary', 'connection-error': 'border-destructive/30 bg-destructive/10 text-destructive', 'coming-soon': 'border-border bg-muted text-muted-foreground' }
export function providerHasEnvConfig(id: string) { return integrations.find((integration) => integration.id === id)?.envKeys ?? [] }

